### ISSUE TITLE
coCondenser MS-MARCO Passage Retrieval example raises error

### ISSUE THREAD

**Issue by YuLengsen** [texttron/tevatron#15] opened 2021-10-29 03:05 UTC
I'm trying to reproduce this example: [(https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco)]

Inference with fine-tuned checkpoint(encode and Index-search) are all good, however, fine-tuning stage 1 (training) raises an error:
`Downloading and preparing dataset json/default (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to /home/dmx/.cache/huggingface/datasets/json/default-e642d34fc5e4ebf2/0.0.0/793d004298099bd3c4e61eb7878475bcf1dc212bf2e34437d85126758720d7f9...
10/29/2021 10:44:35 - WARNING - datasets.builder -   Using custom data configuration default-e642d34fc5e4ebf2
Traceback (most recent call last):
  File "/home/dmx/anaconda3/lib/python3.8/site-packages/tevatron/driver/train.py", line 117, in <module>
    main()
  File "/home/dmx/anaconda3/lib/python3.8/site-packages/tevatron/driver/train.py", line 82, in main
    train_dataset = TrainDataset(
  File "/home/dmx/anaconda3/lib/python3.8/site-packages/tevatron/data.py", line 29, in __init__
    self.train_data = datasets.load_dataset(
  File "/home/dmx/anaconda3/lib/python3.8/site-packages/datasets-1.9.0-py3.8.egg/datasets/load.py", line 856, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/dmx/anaconda3/lib/python3.8/site-packages/datasets-1.9.0-py3.8.egg/datasets/builder.py", line 583, in download_and_prepare
    self._download_and_prepare(
  File "/home/dmx/anaconda3/lib/python3.8/site-packages/datasets-1.9.0-py3.8.egg/datasets/builder.py", line 639, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/home/dmx/anaconda3/lib/python3.8/site-packages/datasets-1.9.0-py3.8.egg/datasets/packaged_modules/json/json.py", line 46, in _split_generators
    raise ValueError(f"At least one data file must be specified, but got data_files={self.config.data_files}")
ValueError: At least one data file must be specified, but got data_files=None`

I think the problem maybe come from lines 25~32 of tevatron.driver.train.py, but I don't know the specific reason or how to solve it:
`        if isinstance(path_to_data, datasets.Dataset):
            self.train_data = path_to_data
        else:
            self.train_data = datasets.load_dataset(
                'json',
                data_dir=path_to_data,
                ignore_verifications=False,
            )['train']
`

**Comment by MXueguang** [comment] 2021-10-29 18:53
did you download the condenser checkpoint into local?
see if setting this line to `None` will help?
https://github.com/texttron/tevatron/blob/3cef7da6368827d9b8cf6d6c40db380b584c1752/src/tevatron/driver/train.py#L111

**Comment by luyug** [comment] 2021-10-29 19:07
If this does not solve it, since we are currently not able to able to reproduce the error,  you probably need to try a clean install.

**Comment by YuLengsen** [comment] 2021-10-30 13:45
A clean install is helpful and the error has disappeared. Thanks for your help!

**Comment by luyug** [comment] 2021-10-30 17:33
Closing as TOT is good.

**Closed by luyug** 2021-10-30 17:33 UTC
